variables:
    RYE_VERSION: "0.39"
    RYE_IMAGE: "jfxs/rye"

stages:
  - test
  - lint
#  - build

# The Docker image (always latest or use the variables?)
image: jfxs/rye

test-py_3.11:
  stage: test
  script:
    - echo "Rye environment version"
    - rye --version
    - echo "Pinning 3.11"
    - rye pin 3.11
    - rye sync
    - echo "Using python version:"
    - python --version
    - echo "Running tests with Rye"
    - rye test

test-py_3.12:
  stage: test
  script:
    - echo "Rye environment version"
    - rye --version
    - echo "Pinning 3.12"
    - rye pin 3.12
    - rye sync
    - echo "Using python version:"
    - python --version
    - echo "Running tests with Rye"
    - rye test

lint:
  stage: lint
  script:
    - echo "Rye environment version"
    - rye --version
    - echo "Using python version:"
    - python --version
    - echo "Running rye lint"
    - rye lint


