stages:
  #- test
  #- lint
  - nightly-test
  - prepare
  - deploy
  

variables:
  UV_CACHE_DIR: "$CI_PROJECT_DIR/.uv-cache"

cache:
  key:
    files:
      - uv.lock
  paths:
    - .uv-cache

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
      when: always
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - when: never
    
# run on any push
#pytest:
#  stage: test
#  rules:
#    - if: $CI_PIPELINE_SOURCE == "schedule"
#      when: never
#    - when: always
#  parallel:
#    matrix:
#      - PYTHON_VERSION: ["3.11", "3.12", "3.13"]
#  script:
#    - uv python install $PYTHON_VERSION
#    - uv run --python $PYTHON_VERSION pytest

## Linting (Ruff normally only needs one python version): run on any push 
#lint-ruff:
#  stage: lint
#  rules:
#    - if: $CI_PIPELINE_SOURCE == "schedule"
#      when: never
#    - when: always
#  script:
#    - uv run ruff check src



# Nightly matrix: force fresh environments and dependency upgrades
nightly-pytest:
  stage: nightly-test
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - when: never
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.11", "3.12", "3.13"]
  script:
    - uv python install $PYTHON_VERSION
    - uv run --python $PYTHON_VERSION pytest




create_release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cli:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  before_script:
    - apk add --no-cache gawk curl

  script:
    - VERSION_RAW=$(awk -F ' = ' '/^\[project\]/{in_proj=1; next} /^\[/{in_proj=0} in_proj && /^version/{gsub(/"/, "", $2); print $2; exit}' pyproject.toml)
    - RELEASE_VERSION="v${VERSION_RAW}"
    - echo "RELEASE_VERSION=$RELEASE_VERSION" >> release.env
    #- |
    #  curl --request POST \
    #    --header "JOB-TOKEN: $CI_JOB_TOKEN" \
    #    --form "tag_name=$RELEASE_VERSION" \
    #    --form "ref=$CI_COMMIT_SHA" \
    #    "https://$CI_SERVER_HOST/api/v4/projects/$CI_PROJECT_ID/repository/tags"
    - echo "Creating release for $RELEASE_VERSION..."
    - GITLAB_TOKEN=$CI_JOB_TOKEN GLAB_HOST=$CI_SERVER_HOST glab release create "$RELEASE_VERSION" --repo "$CI_PROJECT_PATH" --name "Release $RELEASE_VERSION" --notes "Automatic release for commit $CI_COMMIT_TITLE" --ref $CI_COMMIT_SHA
  artifacts:
    reports:
      # Make $RELEASE_VERSION accessible in jext job
      dotenv: release.env

publish_pypi:
  stage: deploy
  image: ghcr.io/astral-sh/uv:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  dependencies:
    - create_release
  script:
    - uv build
    - uv publish