"Tests the for datastreams module of the gams3 package."

from pathlib import Path

from gamspreprocessor.gams3.datastream import DataStream


def _mock_datastream_response(monkeypatch, make_fake_response, payload: bytes):
    def fake_get(_url, timeout):
        assert timeout == 30
        return make_fake_response(payload, 200)

    monkeypatch.setattr("gamspreprocessor.gams3.datastream.requests.get", fake_get)

def test_datastream_init():
    "Test the initialization of a DataStream."
    ds = DataStream(
        url="https://example.com/fedora/objects/o%3Afoo.testobject1/datastreams/METADATA",
        dsid="METADATA",
        pid="o:foo.testobject1",
        label="Metadata for test object 1",
        mime_type="text/xml",
    )
    assert ds.url == "https://example.com/fedora/objects/o%3Afoo.testobject1/datastreams/METADATA"
    assert ds.dsid == "METADATA"
    assert ds.pid == "o:foo.testobject1"
    assert ds.label == "Metadata for test object 1"
    assert ds.mime_type == "text/xml"


def test_datastream_content(monkeypatch, lazy_shared_datadir, make_fake_response):
    "Test the content property of a DataStream."

    def fake_get(url, timeout):
        assert timeout == 30
        assert url == "https://example.com/fedora/objects/o%3Afoo.testobject1/datastreams/TEI_SOURCE/content"
        xml = (lazy_shared_datadir / "tei_source.xml").read_bytes()
        return make_fake_response(xml, 200)

    monkeypatch.setattr("gamspreprocessor.gams3.datastream.requests.get", fake_get)

    ds = DataStream(
        url="https://example.com/fedora/objects/o%3Afoo.testobject1/datastreams/TEI_SOURCE",
        dsid="TEI_SOURCE",
        pid="o:foo.testobject1",
        label="TEI Source for test object 1",
        mime_type="text/xml",
    )

    content = ds.content
    assert content == (lazy_shared_datadir / "tei_source.xml").read_bytes()


def test_datastream_content_is_cached(monkeypatch, make_fake_response):
    calls = []

    def fake_get(url, timeout):
        calls.append((url, timeout))
        return make_fake_response(b"cached-content", 200)

    monkeypatch.setattr("gamspreprocessor.gams3.datastream.requests.get", fake_get)

    ds = DataStream(
        url="https://example.com/fedora/objects/o%3Afoo.testobject1/datastreams/TEI_SOURCE",
        dsid="TEI_SOURCE",
        pid="o:foo.testobject1",
        label="TEI Source",
        mime_type="text/xml",
    )

    assert ds.content == b"cached-content"
    assert ds.content == b"cached-content"
    assert len(calls) == 1


def test_is_empty_detects_empty_payload(monkeypatch, make_fake_response):
    _mock_datastream_response(monkeypatch, make_fake_response, b"")

    ds = DataStream(
        url="https://example.com/fedora/objects/o%3Afoo.testobject1/datastreams/EMPTY",
        dsid="EMPTY",
        pid="o:foo.testobject1",
        label="Empty",
        mime_type="application/octet-stream",
    )

    assert ds.is_empty() is True


def test_is_empty_detects_default_access_marker(monkeypatch, make_fake_response):
    _mock_datastream_response(monkeypatch, make_fake_response, b"prefix [DefaulAccess] suffix")

    ds = DataStream(
        url="https://example.com/fedora/objects/o%3Afoo.testobject1/datastreams/METADATA",
        dsid="METADATA",
        pid="o:foo.testobject1",
        label="Metadata",
        mime_type="text/xml",
    )

    assert ds.is_empty() is True


def test_is_empty_detects_generated_text_marker(monkeypatch, make_fake_response):
    _mock_datastream_response(
        monkeypatch,
        make_fake_response,
        b"This was automatically generated by GAMS for testing",
    )

    ds = DataStream(
        url="https://example.com/fedora/objects/o%3Afoo.testobject1/datastreams/INFO",
        dsid="INFO",
        pid="o:foo.testobject1",
        label="Info",
        mime_type="text/plain",
    )

    assert ds.is_empty() is True


def test_is_empty_returns_false_for_real_content(monkeypatch, make_fake_response):
    _mock_datastream_response(
        monkeypatch,
        make_fake_response,
        b"<TEI><text>actual content</text></TEI>",
    )

    ds = DataStream(
        url="https://example.com/fedora/objects/o%3Afoo.testobject1/datastreams/TEI_SOURCE",
        dsid="TEI_SOURCE",
        pid="o:foo.testobject1",
        label="TEI",
        mime_type="text/xml",
    )

    assert ds.is_empty() is False


def test_export_dc_uses_xml_filename(tmp_path: Path, monkeypatch, make_fake_response):
    _mock_datastream_response(monkeypatch, make_fake_response, b"<dc />")

    ds = DataStream(
        url="https://example.com/fedora/objects/o%3Afoo.testobject1/datastreams/DC",
        dsid="DC",
        pid="o:foo.testobject1",
        label="Dublin Core",
        mime_type="text/xml",
    )

    result = ds.export(tmp_path)

    assert result is not None
    assert result.name == "DC.xml"


def test_export_warns_on_unknown_mime_type(recwarn, tmp_path: Path, monkeypatch, make_fake_response):
    _mock_datastream_response(monkeypatch, make_fake_response, b"custom")

    ds = DataStream(
        url="https://example.com/fedora/objects/o%3Afoo.testobject1/datastreams/CUSTOM",
        dsid="CUSTOM",
        pid="o:foo.testobject1",
        label="Custom",
        mime_type="application/x-unknown-type",
    )

    result = ds.export(tmp_path)

    assert result is not None
    assert result.name == "CUSTOM"
    assert len(recwarn) == 1


def test_export_returns_none_for_ignored_datastream(
    tmp_path: Path, monkeypatch, make_fake_response
):
    _mock_datastream_response(monkeypatch, make_fake_response, b"ignored")

    ds = DataStream(
        url="https://example.com/fedora/objects/o%3Afoo.testobject1/datastreams/PID",
        dsid="PID",
        pid="o:foo.testobject1",
        label="Persistent Identifier",
        mime_type="text/plain",
    )

    result = ds.export(tmp_path)

    assert result is None


def test_export_writes_special_datastream_to_subdirectory(
    tmp_path: Path, monkeypatch, make_fake_response
):
    _mock_datastream_response(monkeypatch, make_fake_response, b"<xml>metadata</xml>")

    ds = DataStream(
        url="https://example.com/fedora/objects/o%3Afoo.testobject1/datastreams/METADATA",
        dsid="METADATA",
        pid="o:foo.testobject1",
        label="Metadata",
        mime_type="text/xml",
    )

    result = ds.export(tmp_path)

    assert result is not None
    assert result.parent.name == "special_datastreams"
    assert result.name == "METADATA.xml"
    assert result.read_bytes() == b"<xml>metadata</xml>"


def test_export_writes_regular_datastream_to_object_directory(
    tmp_path: Path, monkeypatch, make_fake_response
):
    _mock_datastream_response(monkeypatch, make_fake_response, b"<TEI/>")

    ds = DataStream(
        url="https://example.com/fedora/objects/o%3Afoo.testobject1/datastreams/TEI_SOURCE",
        dsid="TEI_SOURCE",
        pid="o:foo.testobject1",
        label="TEI",
        mime_type="text/xml",
    )

    result = ds.export(tmp_path)

    assert result is not None
    assert result.parent == tmp_path
    assert result.name == "TEI_SOURCE.xml"
    assert result.read_bytes() == b"<TEI/>"