"A datastream of a Fedora 3 object."

from dataclasses import dataclass, field
import mimetypes
from pathlib import Path
from typing import Final
import warnings
import requests


# These are datastream ids which should be treated differently, as they are not regular content 
# datastreams but rather metadata or system datastreams. (We put them in a separate subdirectory
SPECIAL_DS_IDS: frozenset[str] = frozenset((
    "DC_MAPPING",
    "FO_STYLESHEET",
    "HSS_STYLESHEET",
    "LATEX_STYLESHEET",
    "METADATA",
    "METHODS",
    "QUERYRDF_MAPPING",
    "RDF",
    "RELS-EXT",
    "RELS-INT",
    "REPLACEMENT_RULESET",
    "STYLESHEET",
    "SOURCE_REF",
    "TORDF",
))
    
# These datastream ids are not exported
IGNORE_DS_IDS: frozenset[str] = frozenset((
    "METS_REF",
    "PID",
    "VOYANT",
    "QR",
    "THUMBNAIL",
))

# name of the subdirectory where datastreams with an id contained in SPECIAL_DS_IDS are stored
SPECIAL_DIR_NAME: Final[str] = "special_datastreams"


@dataclass
class DataStream:
    "A datastream of a Fedora 3 object."

    url: str
    dsid: str
    pid: str
    label: str
    mime_type: str
    # if requesting fails, we set it to None to avoid re-requesting it
    _content: bytes|None = field(init=False, default=b"")


    @property
    def content(self):
        """Return the content of the datastream as bytes.
        
        If the content is not available (e.g. because the datastream is empty 
        or the request fails), return an empty byte string.
        """
        if self._content is None:
            return b""
        if not self._content:
            response = requests.get(f"{self.url}/content", timeout=30)
            if response.status_code >= 400:  # noqa: PLR2004
                self._content = None
            else:
                self._content = response.content
        return self._content

    def export(self, output_dir: Path) -> Path | None:
        """Export the datastream content to a file in the given output directory."""
        if self.dsid in IGNORE_DS_IDS or self.is_empty() :
            return None
        if self.dsid in SPECIAL_DS_IDS:
            ds_path = output_dir / SPECIAL_DIR_NAME / f"{self._get_filename()}"
            ds_path.parent.mkdir(parents=True, exist_ok=True)
        else:
            ds_path = output_dir / f"{self._get_filename()}"
        with open(ds_path, "wb") as f:
            f.write(self.content)
        return ds_path

    def is_empty(self) -> bool:
        """Return True if the datastream is empty (i.e. has no content), False otherwise."""
        if self.content is None or len(self.content) == 0:
            return True
        # It seems that all datastreams have default values (which might have changed over time)
        # 'DefaulAccess' is NOT A TYPE here: This is what is returned
        if b'[DefaulAccess]' in self.content:
            return True
        return (
            self.mime_type.startswith("text/")
            and b'automatically generated by GAMS' in self.content
        )

    def __str__(self):
        return f"DataStream(dsid={self.dsid})"

    def _get_filename(self):
        """Return a safe filename for the datastream, based on its dsid and mime type.

        As GAMS 3 datastreams do not have extensions, we need to guess it based on the mime type.
        If the mime type is not recognized, we just use the dsid as filename.
        """
        # this ony is always there
        if self.dsid == "DC":
            return "DC.xml"

        extension = mimetypes.guess_extension(self.mime_type) if self.mime_type else ""
        extension = extension or ""
        if not extension:
            warnings.warn(
                f"Could not guess file extension for datastream {self.dsid} "
                f"with mime type {self.mime_type}. Using dsid as filename."
            )
        # Use dsid as base filename, and append label if it exists and is not the same as dsid
        # Replace any characters that are not safe for filenames with underscores
        safe_name = "".join(c if c.isalnum() or c in "-_." else "_" for c in self.dsid)
        return safe_name + extension
